### ISSUE TITLE
GeoPort 3.0 Loading Issue - Mac OS X 15.1.1 / Apple Macbook Pro M1 Pro

### ISSUE THREAD

**Issue by spagasaurus** [davesc63/GeoPort#127]
Unable to start GeoPort after installing the new 3.0 version. Running Mac OS X 15.1.1 on Apple Macbook Pro M1 Pro. Restarted after installing. Uninstalled and reinstalled - same issue as below.

---

​Traceback (most recent call last):
  File "importlib/metadata/__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pymobiledevice3/cli/mounter.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pymobiledevice3/cli/cli_common.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/prompt.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/render/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/render/console/__init__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/events.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "readchar/__init__.py", line 6, in <module>
  File "importlib/metadata/__init__.py", line 1009, in version
  File "importlib/metadata/__init__.py", line 982, in distribution
  File "importlib/metadata/__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for readchar
[PYI-1178:ERROR] Failed to execute script 'main' due to unhandled exception: No package metadata was found for readchar
[PYI-1178:ERROR] Traceback:
Traceback (most recent call last):
  File "importlib/metadata/__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pymobiledevice3/cli/mounter.py", line 8, in <module>
    from pymobiledevice3.cli.cli_common import Command, print_json
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pymobiledevice3/cli/cli_common.py", line 12, in <module>
    import inquirer3
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/prompt.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/render/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/render/console/__init__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "inquirer3/events.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "readchar/__init__.py", line 6, in <module>
  File "importlib/metadata/__init__.py", line 1009, in version
  File "importlib/metadata/__init__.py", line 982, in distribution
  File "importlib/metadata/__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for readchar

**Comment by davesc63** [comment]
working on it - pipeline needs updating

**Comment by davesc63** [comment]
v3.0.0 Released
