### ISSUE TITLE
Error connecting 

### ISSUE THREAD

**Issue by Leynoxxx** [davesc63/GeoPort#22]
When I run the program, my device (Iphone SE 2020 with ios 17.0) appears in the list of devices, but when I choose Connect Device, it show Error Connecting. And in the console : "Connected Devices: {'00008030-001059343610402E': {'USB': [{'Identifier': '00008030-001059343610402E', 'DeviceClass': 'iPhone', 'DeviceName': 'Elouan’s Iphone14ProMax2to5G', 'BuildVersion': '21A329', 'ProductVersion': '17.0', 'ProductType': 'iPhone12,8', 'ConnectionType': 'USB', 'wifiState': True}]}}

2024-04-18 14:25:11 DESKTOP-6IJIJV5 GeoPort[7548] INFO Connect Device Data: {'udid': '00008030-001059343610402E', 'ios_version': '17.0', 'connType': 'USB', 'wifiState': True}
2024-04-18 14:25:11 DESKTOP-6IJIJV5 GeoPort[7548] WARNING Check Developer Mode
2024-04-18 14:25:11 DESKTOP-6IJIJV5 main-win[7548] ERROR Exception on /connect_device [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "main-win.py", line 433, in connect_device
  File "main-win.py", line 315, in check_developer_mode
  File "pymobiledevice3\lockdown.py", line 256, in developer_mode_status
  File "pymobiledevice3\lockdown.py", line 56, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 378, in get_value
  File "pymobiledevice3\lockdown.py", line 500, in _request
pymobiledevice3.exceptions.LockdownError: GetProhibited"

Even if my developer mode is enabled on my Iphone. If any of you have an idea of how i can solve this problem, please let me know ! Have a good day

**Comment by kokpek** [comment]
im having the same issue, cant figure out how to work around this

**Comment by thanhdat995** [comment]
![Untitled](https://github.com/davesc63/GeoPort/assets/59078003/640d3efa-d47d-4d0f-8be6-d0d47cd367a3)
I have an Error Connecting on iOS 15.7. Is there any way to fix this error?

**Comment by davesc63** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/59078003/338391307-640d3efa-d47d-4d0f-8be6-d0d47cd367a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzE2NzksIm5iZiI6MTcxODA3MTM3OSwicGF0aCI6Ii81OTA3ODAwMy8zMzgzOTEzMDctNjQwZDNlZmEtZDQ3ZC00ZDBmLThiZTYtZDBkNDdjZDM2N2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MGZhZTg2NzAzYjEwODVlNWI5ZWIxMDEwNDcyNzdiMDYxNjM0MWE2YTc4ODhhZjliNjY0MGQ5NzIwZTg2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIqUlOglWA-nsW47JDKD78UKIDO4KqGn187qtzXxkGY) I have an Error Connecting on iOS 15.7. Is there any way to fix this error?

ios15 not supported.
More donations will help me to buy an old iPhone and develop support for that version
