### ISSUE TITLE
Unable to connect iPhone 13 iOS17

### ISSUE THREAD

**Issue by thedandychiggins** [davesc63/GeoPort#27]
I'm getting the following error trying to connect:

I have developer mode enabled in settings and am running GeoPort as admin.

2024-04-26 22:25:23 NotSkyNet GeoPort[23336] WARNING Check Developer Mode
2024-04-26 22:25:23 NotSkyNet main-win[23336] ERROR Exception on /connect_device [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 882, in full_dispatch_request
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "main-win.py", line 533, in connect_device
  File "main-win.py", line 407, in check_developer_mode
  File "pymobiledevice3\lockdown.py", line 263, in developer_mode_status
  File "pymobiledevice3\lockdown.py", line 62, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 444, in get_value
  File "pymobiledevice3\lockdown.py", line 570, in _request
pymobiledevice3.exceptions.GetProhibitedError: GetProhibited

**Comment by davesc63** [comment]
@thedandychiggins are you on ios15?

can you please share some more of the log from before this?

**Comment by thedandychiggins** [comment]
I'm on iOS 17.4.1

Here's a full log:

2024-04-27 09:31:27 NotSkyNet pyi_splash[24756] INFO A connection to the splash screen was successfully established.
2024-04-27 09:31:27 NotSkyNet GeoPort[24756] INFO clear splash
2024-04-27 09:31:27 NotSkyNet pyuac[24756] INFO isUserAdmin - CheckTokenMembership returned: True
2024-04-27 09:31:27 NotSkyNet GeoPort[24756] INFO Serving: http://localhost:53217
 * Serving Flask app 'main-win'
 * Debug mode: off
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] WARNING Failed to retrieve country name using locale. Using IP geolocation service.
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] INFO Country: United Kingdom
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] INFO Current platform: Windows
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] INFO App Version = 2.2.0
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] INFO base dir =  C:\Users\pc\AppData\Local\Temp\_MEI237722
2024-04-27 09:31:31 NotSkyNet GeoPort[24756] INFO GitHub Version = 2.1.0
2024-04-27 09:31:32 NotSkyNet GeoPort[24756] INFO

Raw Devices:  [MuxDevice(devid=2, serial='00008110000265D901DA801E', connection_type='USB'), MuxDevice(devid=1, serial='00008110-000265D901DA801E', connection_type='Network')]

2024-04-27 09:31:32 NotSkyNet GeoPort[24756] WARNING Failed to retrieve country name using locale. Using IP geolocation service.
2024-04-27 09:31:33 NotSkyNet GeoPort[24756] WARNING Failed to retrieve country name using locale. Using IP geolocation service.
2024-04-27 09:31:33 NotSkyNet GeoPort[24756] INFO

Connected Devices: {'00008110000265D901DA801E': {'USB': [{'Identifier': '00008110000265D901DA801E', 'DeviceClass': 'iPhone', 'DeviceName': 'Phone', 'BuildVersion': '21E236', 'ProductVersion': '17.4.1', 'ProductType': 'iPhone14,5', 'UniqueDeviceID': '00008110-000265D901DA801E', 'ConnectionType': 'USB', 'wifiState': True, 'userLocale': 'United Kingdom'}]}, '00008110-000265D901DA801E': {'Wifi': [{'Identifier': '00008110-000265D901DA801E', 'DeviceClass': 'iPhone', 'DeviceName': 'Phone', 'BuildVersion': '21E236', 'ProductVersion': '17.4.1', 'ProductType': 'iPhone14,5', 'UniqueDeviceID': '00008110-000265D901DA801E', 'ConnectionType': 'Network', 'wifiState': True, 'userLocale': 'United Kingdom'}]}}

2024-04-27 09:31:52 NotSkyNet GeoPort[24756] INFO Connect Device Data: {'udid': '00008110000265D901DA801E', 'ios_version': '17.4.1', 'connType': 'USB', 'wifiState': True}
2024-04-27 09:31:52 NotSkyNet GeoPort[24756] WARNING Check Developer Mode
2024-04-27 09:31:52 NotSkyNet main-win[24756] ERROR Exception on /connect_device [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 882, in full_dispatch_request
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "main-win.py", line 533, in connect_device
  File "main-win.py", line 407, in check_developer_mode
  File "pymobiledevice3\lockdown.py", line 263, in developer_mode_status
  File "pymobiledevice3\lockdown.py", line 62, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 444, in get_value
  File "pymobiledevice3\lockdown.py", line 570, in _request
pymobiledevice3.exceptions.GetProhibitedError: GetProhibited

**Comment by davesc63** [comment]
This may be due to the device not being paired.  
Any pop ups appear on device?

**Comment by thedandychiggins** [comment]
I don't get any popups on the device with screen unlocked and plugged in. I can see it in iTunes though.

**Comment by davesc63** [comment]
@thedandychiggins I'm a bit stumped.
My suggestion would be to disable Developer Mode (Privacy & Security - Developer Mode) 

I think I've seen this as a problem with the pair record that is stored in your user profile, ie `C:\users\UserName\.pymobiledevice3` folder
