### ISSUE TITLE
Issue on iPhone 17.4.1

### ISSUE THREAD

**Issue by axc190072** [davesc63/GeoPort#36]
Still get Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Here is console log:
​2024-05-01 12:35:29 anthos-MacBook-Air.local GeoPort[1593] INFO Running as Sudo
2024-05-01 12:35:29 anthos-MacBook-Air.local GeoPort[1593] INFO Serving: http://localhost:57436
 * Serving Flask app 'main'
 * Debug mode: off
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] WARNING User locale is None. Defaulting to IP geolocation service.
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO Country: United States
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO Current platform: MacOS
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO App Version = 2.3.2
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO base dir =  /var/folders/0j/8tjzf4b510n5bbl9j2n3pvkc0000gn/T/_MEIu51IiY
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO GitHub Version = 2.3.2
2024-05-01 12:35:33 anthos-MacBook-Air.local GeoPort[1593] INFO 

Raw Devices:  [MuxDevice(devid=4, serial='00008110-000275D03450401E', connection_type='Network')]

2024-05-01 12:35:34 anthos-MacBook-Air.local GeoPort[1593] WARNING User locale is None. Defaulting to IP geolocation service.
2024-05-01 12:35:34 anthos-MacBook-Air.local GeoPort[1593] INFO 

Connected Devices: {'00008110-000275D03450401E': {'Wifi': [{'Identifier': '00008110-000275D03450401E', 'DeviceClass': 'iPhone', 'DeviceName': 'iPhone', 'BuildVersion': '21E236', 'ProductVersion': '17.4.1', 'ProductType': 'iPhone14,6', 'UniqueDeviceID': '00008110-000275D03450401E', 'ConnectionType': 'Network', 'wifiState': True, 'userLocale': 'United States'}]}}

2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Connect Device Data: {'udid': '00008110-000275D03450401E', 'ios_version': '17.4.1', 'connType': 'Network', 'wifiState': True}
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] WARNING Check Developer Mode
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Developer Mode Check result:  True
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Developer Mode is true
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Connection Type: Network
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Enable Developer Mode
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Pair Record Home: /Users/antho/.pymobiledevice3
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Pair Record File: remote_00008110-000275D03450401E
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO Wifi data: {'udid': '00008110-000275D03450401E', 'ios_version': '17.4.1', 'connType': 'Network', 'wifiState': True}
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] INFO iOS 17+ detected
2024-05-01 12:35:35 anthos-MacBook-Air.local GeoPort[1593] WARNING Start Wifi TCP Tunnel
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO Identifier: 00008110-000275D03450401E
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO Interface: utun5
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Address: fd81:6323:b435::1
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Port: 49348
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: ('fd81:6323:b435::1', '49348')
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] INFO Device Connection Map: {'00008110-000275D03450401E': {'Network': {'host': 'fd81:6323:b435::1', 'port': '49348'}}}
2024-05-01 12:35:36 anthos-MacBook-Air.local GeoPort[1593] WARNING Connect Device function completed
2024-05-01 12:35:40 anthos-MacBook-Air.local GeoPort[1593] INFO stop set location data:  ('fd81:6323:b435::1', '49348')
2024-05-01 12:35:40 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Cleared Successfully
2024-05-01 12:35:40 anthos-MacBook-Air.local GeoPort[1593] INFO stop set location data:  {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:35:41 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Cleared Successfully
2024-05-01 12:36:20 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:20 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:20 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:20 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:38 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:39 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:40 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:40 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:40 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:40 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:36:41 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:54 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:55 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:56 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:57 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:37:58 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:37:59 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:38:00 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:35 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] WARNING Location Set Successfully
Exception in thread Thread-130 (check_termination):
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD in udid mapping is: {'host': 'fd81:6323:b435::1', 'port': '49348'}
----------------------------------------
Traceback (most recent call last):
----------------------------------------
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD already created. Reusing connection
  File "threading.py", line 1045, in _bootstrap_inner
Exception occurred during processing of request from ('127.0.0.1', 50444)
Exception occurred during processing of request from ('127.0.0.1', 50445)
  File "threading.py", line 982, in run
  File "main.py", line 1002, in check_termination
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] INFO RSD Data: {'host': 'fd81:6323:b435::1', 'port': '49348'}
2024-05-01 12:38:36 anthos-MacBook-Air.local GeoPort[1593] ERROR Error setting location: [Errno 24] Too many open files
  File "asyncio/runners.py", line 189, in run
  File "asyncio/runners.py", line 59, in __enter__
  File "asyncio/runners.py", line 137, in _lazy_init
  File "asyncio/events.py", line 810, in new_event_loop
  File "asyncio/events.py", line 699, in new_event_loop
  File "asyncio/unix_events.py", line 64, in __init__
  File "asyncio/selector_events.py", line 53, in __init__
Traceback (most recent call last):
  File "werkzeug/serving.py", line 362, in run_wsgi
  File "werkzeug/serving.py", line 338, in execute
  File "selectors.py", line 511, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
  File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
OSError: [Errno 24] Too many open files: '/Applications/GeoPort-mac.app/Contents/Resources/GeoPort'

The above exception was the direct cause of the following exception:

**Comment by davesc63** [comment]
You are overloading the device. As mentioned you need to clear old locations by pressing “stop location”

send me the gpx file or whatever you are attempting to do. 

I built in an auto clearing method, however I felt more people would be unhappy with that. Because clearing old connections resets your location back to the real location for a split second

**Comment by axc190072** [comment]
I see. It's important for my usage that the location doesn't reset when clearing old locations. Is there a workaround? Thank you.

**Comment by davesc63** [comment]
Please share how you are using the spoofing so I can understand it better.
At the moment the spoofing service is being flooded with location changes. The work around is to stop location to clear old connections and spoof again.

I can look at some programmatic magic, but I need to understand if its something I really need to add

**Comment by axc190072** [comment]
I am connecting my phone, searching for a location, then pressing simulate location, and then using my arrowkeys to walk around.

**Comment by davesc63** [comment]
Noted thanks. 
I will continue to look at options
