### ISSUE TITLE
Location won't change

### ISSUE THREAD

**Issue by wudok777** [davesc63/GeoPort#39]
Hi,

I've tried this with a couple of iPhones (14 pro on iOS17) and (7 on iOS15) and neither work.  It says that the simulate location is successful but nothing changes on my phone?   Am I doing something wrong?

**Comment by davesc63** [comment]
Please share as much of the server console log as you can. I have no idea what's happening without that.

**Comment by wudok777** [comment]
Actually, now both phones won't connect

2024-05-03 11:25:08 Jean-p-N1V71MJXJD main[68373] ERROR Exception on /connect_device [POST]
Traceback (most recent call last):
  File "flask/app.py", line 1463, in wsgi_app
  File "flask/app.py", line 872, in full_dispatch_request
  File "flask/app.py", line 870, in full_dispatch_request
  File "flask/app.py", line 855, in dispatch_request
  File "main.py", line 433, in connect_device
  File "main.py", line 315, in check_developer_mode
  File "pymobiledevice3/lockdown.py", line 256, in developer_mode_status
    return self.get_value('com.apple.security.mac.amfi', 'DeveloperModeStatus')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 56, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 378, in get_value
    res = self._request('GetValue', options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 500, in _request
    raise exception_errors.get(error, LockdownError)(error)
pymobiledevice3.exceptions.MissingValueError: MissingValue
2024-05-03 11:25:09 Jean-p-N1V71MJXJD GeoPort[68373] INFO Connect Device Data: {'udid': '7297bfb26144b9144980531bdad25dd5c3dfa084', 'ios_version': '15.8.2', 'connType': 'USB', 'wifiState': True}
2024-05-03 11:25:09 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Check Developer Mode
2024-05-03 11:25:09 Jean-p-N1V71MJXJD main[68373] ERROR Exception on /connect_device [POST]
Traceback (most recent call last):
  File "flask/app.py", line 1463, in wsgi_app
  File "flask/app.py", line 872, in full_dispatch_request
  File "flask/app.py", line 870, in full_dispatch_request
  File "flask/app.py", line 855, in dispatch_request
  File "main.py", line 433, in connect_device
  File "main.py", line 315, in check_developer_mode
  File "pymobiledevice3/lockdown.py", line 256, in developer_mode_status
    return self.get_value('com.apple.security.mac.amfi', 'DeveloperModeStatus')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 56, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 378, in get_value
    res = self._request('GetValue', options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pymobiledevice3/lockdown.py", line 500, in _request
    raise exception_errors.get(error, LockdownError)(error)
pymobiledevice3.exceptions.MissingValueError: MissingValue

**Comment by davesc63** [comment]
Yeah ios15 will struggle. I don’t have a device to test against and they don’t implement developer mode

what’s your ios17 device issue?

**Comment by wudok777** [comment]
2024-05-03 12:58:14 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 1: No devices found
2024-05-03 12:58:16 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 2: No devices found
2024-05-03 12:58:18 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 3: No devices found
2024-05-03 12:58:21 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 4: No devices found
2024-05-03 12:58:23 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 5: No devices found
2024-05-03 12:58:25 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 6: No devices found
2024-05-03 12:58:27 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 7: No devices found
2024-05-03 12:58:29 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 8: No devices found
2024-05-03 12:58:31 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 9: No devices found
2024-05-03 12:58:33 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Attempt 10: No devices found
2024-05-03 12:58:34 Jean-p-N1V71MJXJD GeoPort[68373] ERROR Error: No devices found after multiple attempts.
 Ensure you are running GeoPort as sudo / Administrator 
 Please see the FAQ: https://github.com/davesc63/GeoPort/blob/main/FAQ.md 
 If you still have the error please raise an issue on github: https://github.com/davesc63/GeoPort/issues 
2024-05-03 12:58:34 Jean-p-N1V71MJXJD GeoPort[68373] WARNING Connect Device function completed

**Comment by davesc63** [comment]
Please share more of the log. What happens before this? What OS are you using?

This is indicative of a Windows + iOS <17.4 issue
