### ISSUE TITLE
v1.02 on x86 mac cannot execute binary file

### ISSUE THREAD

**Issue by IceSt0rm** [davesc63/GeoPort#4]
intel macbook air 2017 on sonoma. would also like to note version 1.00 still works perfectly

***terminal log***

Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/cli/mounter.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/cli/cli_common.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/remote/remote_service_discovery.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/remote/bonjour.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/__init__.py", line 26, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/_core.py", line 32, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/_engine.py", line 38, in <module>
  File "src/zeroconf/_listener.py", line 1, in init zeroconf._listener
  File "src/zeroconf/_services/info.py", line 1, in init zeroconf._services.info
ModuleNotFoundError: No module named 'zeroconf._utils.ipaddress'
[14824] Failed to execute script 'main' due to unhandled exception: No module named 'zeroconf._utils.ipaddress'
[14824] Traceback:
Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/cli/mounter.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/cli/cli_common.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/remote/remote_service_discovery.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3/remote/bonjour.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/__init__.py", line 26, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/_core.py", line 32, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "zeroconf/_engine.py", line 38, in <module>
  File "src/zeroconf/_listener.py", line 1, in init zeroconf._listener
  File "src/zeroconf/_services/info.py", line 1, in init zeroconf._services.info
ModuleNotFoundError: No module named 'zeroconf._utils.ipaddress'

**Comment by davesc63** [comment]
Thank you for raising. Yep, I can fix this. PyInstaller being painful again

**Comment by davesc63** [comment]
@IceSt0rm - Updated, please try: https://github.com/davesc63/GeoPort/releases/download/v1.0.2/GeoPort-mac-x86-v1.0.2.zip
